CREATE TABLE [dbo].[Certificate]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [UserId] INT NOT NULL FOREIGN KEY REFERENCES [User] (Id) ON DELETE CASCADE,
	[Result] INT NOT NULL, 
    [CourseId] INT NOT NULL FOREIGN KEY REFERENCES [Course] (Id) ON DELETE CASCADE,
)
