CREATE TABLE [dbo].[Course]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL,
	[CategoryId] INT NOT NULL FOREIGN KEY REFERENCES Category(Id)
)
