CREATE TABLE [dbo].[CourseForUser]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [UserId] INT NOT NULL FOREIGN KEY REFERENCES [User] (Id) ON DELETE CASCADE, 
    [CourseId] INT NOT NULL FOREIGN KEY REFERENCES [Course] (Id) ON DELETE CASCADE,
)
