CREATE TABLE [dbo].[TestOption]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[TestId] INT NOT NULL FOREIGN KEY REFERENCES Test (Id) ON DELETE CASCADE,
	[Name] NVARCHAR(50) NOT NULL, 
	[IsChecked] BIT NOT NULL,
)
