CREATE TABLE [dbo].[UserRole]
(
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [User] (Id) ON DELETE CASCADE,
	[RoleId] INT NOT NULL FOREIGN KEY REFERENCES [Role] (Id) ON DELETE CASCADE,
	PRIMARY KEY (UserId, RoleId)
)
