CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY (Id), 
    [Name] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL UNIQUE INDEX IX_Email NONCLUSTERED, 
    [PasswordHash] NVARCHAR(MAX) NOT NULL 
)