//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPortal.Web.Data.LessonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LessonDto", Namespace="http://schemas.datacontract.org/2004/07/TrainingPortal.Service.Dto")]
    [System.SerializableAttribute()]
    public partial class LessonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LessonService.ILessonService")]
    public interface ILessonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILessonService/GetList", ReplyAction="http://tempuri.org/ILessonService/GetListResponse")]
        TrainingPortal.Web.Data.LessonService.LessonDto[] GetList(string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILessonService/Get", ReplyAction="http://tempuri.org/ILessonService/GetResponse")]
        TrainingPortal.Web.Data.LessonService.LessonDto Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILessonService/Update", ReplyAction="http://tempuri.org/ILessonService/UpdateResponse")]
        void Update(TrainingPortal.Web.Data.LessonService.LessonDto lesson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILessonService/Create", ReplyAction="http://tempuri.org/ILessonService/CreateResponse")]
        void Create(TrainingPortal.Web.Data.LessonService.LessonDto lesson, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILessonService/Delete", ReplyAction="http://tempuri.org/ILessonService/DeleteResponse")]
        void Delete(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILessonServiceChannel : TrainingPortal.Web.Data.LessonService.ILessonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LessonServiceClient : System.ServiceModel.ClientBase<TrainingPortal.Web.Data.LessonService.ILessonService>, TrainingPortal.Web.Data.LessonService.ILessonService {
        
        public LessonServiceClient() {
        }
        
        public LessonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LessonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LessonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LessonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrainingPortal.Web.Data.LessonService.LessonDto[] GetList(string courseId) {
            return base.Channel.GetList(courseId);
        }
        
        public TrainingPortal.Web.Data.LessonService.LessonDto Get(string id) {
            return base.Channel.Get(id);
        }
        
        public void Update(TrainingPortal.Web.Data.LessonService.LessonDto lesson) {
            base.Channel.Update(lesson);
        }
        
        public void Create(TrainingPortal.Web.Data.LessonService.LessonDto lesson, string courseId) {
            base.Channel.Create(lesson, courseId);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
    }
}
