//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPortal.Web.Data.AudienceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AudienceDto", Namespace="http://schemas.datacontract.org/2004/07/TrainingPortal.Service.Dto")]
    [System.SerializableAttribute()]
    public partial class AudienceDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AudienceService.IAudienceService")]
    public interface IAudienceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudienceService/GetList", ReplyAction="http://tempuri.org/IAudienceService/GetListResponse")]
        TrainingPortal.Web.Data.AudienceService.AudienceDto[] GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudienceService/Get", ReplyAction="http://tempuri.org/IAudienceService/GetResponse")]
        TrainingPortal.Web.Data.AudienceService.AudienceDto Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudienceService/Update", ReplyAction="http://tempuri.org/IAudienceService/UpdateResponse")]
        void Update(TrainingPortal.Web.Data.AudienceService.AudienceDto audience);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudienceService/Create", ReplyAction="http://tempuri.org/IAudienceService/CreateResponse")]
        void Create(TrainingPortal.Web.Data.AudienceService.AudienceDto audience);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAudienceService/Delete", ReplyAction="http://tempuri.org/IAudienceService/DeleteResponse")]
        void Delete(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAudienceServiceChannel : TrainingPortal.Web.Data.AudienceService.IAudienceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AudienceServiceClient : System.ServiceModel.ClientBase<TrainingPortal.Web.Data.AudienceService.IAudienceService>, TrainingPortal.Web.Data.AudienceService.IAudienceService {
        
        public AudienceServiceClient() {
        }
        
        public AudienceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AudienceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudienceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AudienceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrainingPortal.Web.Data.AudienceService.AudienceDto[] GetList() {
            return base.Channel.GetList();
        }
        
        public TrainingPortal.Web.Data.AudienceService.AudienceDto Get(string id) {
            return base.Channel.Get(id);
        }
        
        public void Update(TrainingPortal.Web.Data.AudienceService.AudienceDto audience) {
            base.Channel.Update(audience);
        }
        
        public void Create(TrainingPortal.Web.Data.AudienceService.AudienceDto audience) {
            base.Channel.Create(audience);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
    }
}
