//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPortal.Web.Data.UserRoleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserRoleService.IUserRoleService")]
    public interface IUserRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/GetList", ReplyAction="http://tempuri.org/IUserRoleService/GetListResponse")]
        string[] GetList(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/Exist", ReplyAction="http://tempuri.org/IUserRoleService/ExistResponse")]
        bool Exist(string userId, string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/Create", ReplyAction="http://tempuri.org/IUserRoleService/CreateResponse")]
        void Create(string userId, string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserRoleService/Delete", ReplyAction="http://tempuri.org/IUserRoleService/DeleteResponse")]
        void Delete(string userId, string roleName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserRoleServiceChannel : TrainingPortal.Web.Data.UserRoleService.IUserRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserRoleServiceClient : System.ServiceModel.ClientBase<TrainingPortal.Web.Data.UserRoleService.IUserRoleService>, TrainingPortal.Web.Data.UserRoleService.IUserRoleService {
        
        public UserRoleServiceClient() {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserRoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetList(string userId) {
            return base.Channel.GetList(userId);
        }
        
        public bool Exist(string userId, string roleName) {
            return base.Channel.Exist(userId, roleName);
        }
        
        public void Create(string userId, string roleName) {
            base.Channel.Create(userId, roleName);
        }
        
        public void Delete(string userId, string roleName) {
            base.Channel.Delete(userId, roleName);
        }
    }
}
